### ISSUE TITLE
Republish boxes

### ISSUE THREAD

**Issue by mcandre** [boxcutter/bsd#35]
The links to the published boxes are now 404'ing. Could these be republished to Vagrant Cloud?

**Comment by rickard-von-essen** [comment]
Unfortunately I think there is not much builds being done for this repos since some time. I have a plan to automate this and move it out to a new repo and republish everything. But that will most likely not happen until Q2 next year.

**Comment by misheska** [comment]
We no longer provide built versions of the boxes
