### ISSUE TITLE
Default disk partitions in openbsd58 do not allow build of xenocara for dev

### ISSUE THREAD

**Issue by rbevers** [boxcutter/bsd#9]
I am trying to use `boxcutter/openbsd58` to do dev work on OpenBSD 5.8. OpenBSD development seems very sensitive to where the source lives. As far as I can tell, it has to be in `/usr/src` for building ports, etc.

To avoid issues I follow the instructions here strictly: http://www.openbsd.org/anoncvs.html#starting

Using `doas` I attempt to build `ports/editors/vim` in the `/usr/` folder. It gives this:

```
$ pwd
/usr/ports/editors/vim
$ doas make
Fatal: building ports requires correctly installed X11 (in editors/vim)
*** Error 1 in /usr/ports/editors/vim (/usr/ports/infrastructure/mk/bsd.port.mk:3567 '.BEGIN': @exit 1)
```

So I attempt to build `xenocara` to have all the deps for `vim`, per its README, like this:

```
$ cd /usr/xenocara
$ make bootstrap
$ make obj
$ make build
```

Unfortunately, my `/usr` partition is too small and I eventually get an out of space error. How do I revise the partition sizes for the `boxcutter/openbsd58` box to expand my `/usr` to be big enough to get development done on there?

```
/usr: write failed, file system is full
gzip: stdout: No space left on device
*** Error 1 in font/adobe-75dpi/obj (Makefile:787 'timR10-ISO8859-1.pcf.gz')
*** Error 1 in font/adobe-75dpi (/usr/X11R6/share/mk/bsd.xorg.mk:145 'all')
*** Error 1 in font/adobe-75dpi (/usr/X11R6/share/mk/bsd.xorg.mk:211 'build')
*** Error 1 in font (<bsd.subdir.mk>:48 'build')
*** Error 1 in . (<bsd.subdir.mk>:48 'realbuild')
*** Error 1 in /usr/xenocara (Makefile:41 'build')
```

**Comment by rickard-von-essen** [comment]
The standard partition layout only sets up 2G for `/usr`. If you want a ports tree I would recommend to add a extra disk in the Vagrant file and then mount it specifically for `/usr/ports`

For parallels I do:

``` ruby
  config.vm.provider "parallels" do |prl|
      prl.customize ["set", :id, "--device-add", "hdd", "--size", "10240", "--iface", "ide", "--connect"]
  end
```

And then I run: fdisk, disklabel, newfs, and edit the `/etc/fstab`.

**Comment by rbevers** [comment]
Thank you for the tip, Rickard. That is a clue that will help me. 

I will dive into the virtualbox capabilities to see how I can control disk partition tables for OpenBSD through the Vagrant config and front-end, if possible.
